### PR TITLE
Update ecstasy.cabal

### PR DESCRIPTION
**Pull request by nek0**
bump "base" version limit

### CODE REVIEW

**Comment by isovector** [comment]
:+1: maybe we should just make this < 5.0?

**Comment by nek0** [comment]
Since there is no TH involved, yeah.

**Comment by isovector** [comment]
thanks!!

**Comment by nek0** [comment]
can you update the package also on hackage, please?

**Comment by isovector** [comment]
done! https://hackage.haskell.org/package/ecstasy-0.1.0.1

**Pull request merged**
